<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="contextAwareModeling" nsURI="http://www.example.org/contextAwareModeling"
    nsPrefix="contextAwareModeling">
  <eClassifiers xsi:type="ecore:EClass" name="State">
    <eStructuralFeatures xsi:type="ecore:EReference" name="action" lowerBound="1"
        upperBound="-1" eType="#//Action" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" ordered="false" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" iD="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Action" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetState" lowerBound="1"
        eType="#//State"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FirstOrderManager">
    <eStructuralFeatures xsi:type="ecore:EReference" name="states" lowerBound="2"
        upperBound="-1" eType="#//State" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ActiveAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="executionRate" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PassiveAction" eSuperTypes="#//Action">
    <eStructuralFeatures xsi:type="ecore:EReference" name="v1_triggerAction" lowerBound="1"
        eType="#//ActiveAction"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="v1_probability" ordered="false"
        unique="false" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDouble"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ContextAwareModel">
    <eStructuralFeatures xsi:type="ecore:EReference" name="firstordermanager" upperBound="-1"
        eType="#//FirstOrderManager" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
